[package]
name = "which"
version = "0.1.0"
authors = ["realityone <realityone@me.com>"]

[dependencies]
uucore = { path = "coreutils/src/uucore" }
which-rs = { path = "../../" }

[[bin]]
name = "which-rs"
path = "src/main.rs"
